version: "3.4"

services:
  masterpay:
    build:
      context: .
    container_name: masterpay
    hostname: masterpay
    restart: always
    volumes:
    - .:/opt/app/
    depends_on:
      - server-callback

  server-callback:
    build:
      context: ./server-callback
    container_name: server-callback
    hostname: server-callback
    restart: always
    ports:
    - 9292:9292
    volumes:
      - .:/opt/app/
