version: "3.4"

services:
  rspec-tests:
    build:
      context: .
    container_name: masterpay
    hostname: masterpay
    restart: always
    volumes:
    - .:/opt/app/

#  postgresql:
#    image: postgres:9.6-alpine
#    container_name: postgresql
#    hostname: postgresql
#    restart: always
#    env_file:
#      - ./env/postgresql.env
#    ports:
#      - '5432:5432'
#    volumes:
#      - postgresql_data:/var/lib/postgresql/data
#      - ./shared/postgres:/data
#  redis:
#    image: redis:3-alpine
#    container_name: redis
#    hostname: redis
#    restart: always
#
#  rabbit:
#    image: rabbitmq:3.7-management-alpine
#    container_name: rabbit
#    hostname: rabbit
#    restart: always
#    env_file:
#      - ./env/rabbitmq.env
#    ports:
#      - "5671:5671"
#      - "5672:5672"
#      - "15672:15672"
#
#  squid:
#    image: sameersbn/squid
#    container_name: squid
#    hostname: squid
#    ports:
#      - '3128:3128'
#
#  server-callbacks:
#    build:
#      context: ./containers/server-callbacks
#    container_name: server-callbacks
#    hostname: server-callbacks
#    ports:
#      - '9292:9292'
#
#  meringue:
#    build:
#      context: ./containers/meringue
#    container_name: meringue
#    command: /meringue s
#    hostname: meringue
#    env_file:
#      - ./env/cryptopay.env
#    environment:
#      - LEVEL=dev
#    ports:
#      - '8081:8081'
#
#  moron:
#    build:
#      context: ./containers/moron
#    container_name: moron
#    command: /moron s
#    hostname: moron
#    env_file:
#      - ./env/cryptopay.env
#    environment:
#      - LEVEL=dev
#    ports:
#      - '8080:8080'
#
#
#  cryptopay:
#    image: cpay/cryptopay:master
#    container_name: cryptopay
#    command: tail -f /dev/null
#    hostname: cryptopay
#    env_file:
#      - ./env/postgresql.env
#      - ./env/cryptopay.shared.env
#      - ./env/cryptopay.env
#      - ./env/bit_go_cryptopay.env #if need fake bitgo meringue
#    volumes:
#      - ./cryptopay:/app
#      - ./shared/ruby:/shared
#    ports:
#      - '3000:3000'
#      - '8999:8999'
#    depends_on:
#      - postgresql
#      - redis
#      - rabbit
#      - moron
#      - meringue
#      - squid
#      - server-callbacks
#
#  cryptopay-admin:
#    image: cpay/cryptopay-admin:master
#    container_name: cryptopay-admin
#    hostname: cryptopay-admin
#    command: tail -f /dev/null
#    env_file:
#      - ./env/postgresql.env
#      - ./env/cryptopay.shared.env
#      - ./env/cryptopay-admin.env
#      - ./env/bit_go_admin.env  #if need fake bitgo meringue
#    volumes:
#      - ./cryptopay-admin:/app
#      - ./shared/ruby:/shared
#    ports:
#      - '3002:3002'
#    depends_on:
#      - postgresql
#      - redis
#      - rabbit

#volumes:
#  postgresql_data:
#    driver: local
#  redis_data:
#    driver: local
