source 'https://rubygems.org'

group :test do
  gem 'allure-rspec'
  gem 'allure-ruby-adaptor-api'
  gem 'chromedriver-helper'
  gem 'colorize'
  gem 'dotenv'
  gem 'dry-container'
  gem 'dry-monads', '>= 1.0.0.rc1', require: 'dry/monads/all'
  gem 'dry-schema'
  gem 'dry-validation'
  gem 'fuubar'
  gem 'hash_dot'
  gem 'json-schema'
  gem 'net-ssh'
  gem 'parallel_tests', group: %i[development test]
  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-doc'
  gem 'rake'
  gem 'rakeup'
  gem 'rest-client'
  gem 'rspec', '~> 3.7'
  gem 'rspec-its'
  gem 'rubocop-rspec'
  gem 'selenium-webdriver'
  gem 'shoulda'
  gem 'test-prof'
  # gem 'capybara'
end